---
- name: add zabbix repo (EL8)
  yum:
    name: 'https://repo.zabbix.com/zabbix/6.2/rhel/8/x86_64/zabbix-release-6.2-3.el8.noarch.rpm'
    state: present
    disable_gpg_check: True
  environment: "{{ proxy_env }}"
  when: ansible_distribution_major_version == "8"

- name: add zabbix repo (EL7)
  yum:
    name: 'https://repo.zabbix.com/zabbix/6.2/rhel/7/x86_64/zabbix-release-6.2-3.el7.noarch.rpm'
    state: present
    disable_gpg_check: True
  environment: "{{ proxy_env }}"
  when: ansible_distribution_major_version == "7"

