---
- name: Enable EPEL Repository on CentOS 8
  dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
    state: present
    disable_gpg_check: True
  environment: "{{ proxy_env }}"

- name: add zabbix repo
  dnf:
    name: 'https://repo.zabbix.com/zabbix/6.2/rhel/8/x86_64/zabbix-release-6.2-3.el8.noarch.rpm'
    state: present
    disable_gpg_check: True
  environment: "{{ proxy_env }}"

- name: run dnf clean all
  shell: dnf clean all
